
name: 'Deploy to docker'
description: 'Build app image and deploy to specific docker registry'
branding:
  icon: 'box'
  color: 'green'

inputs:
  registry:
    description: 'Docker registry'
    required: false
    default: 'registry.cn-shenzhen.aliyuncs.com'
  username:
    description: 'Docker username'
    required: true
  password:
    description: 'Docker password'
    required: true
  repository:
    description: 'Namespace and repository. format: namespace/repository'
    required: true
  tag:
    description: 'Image tag'
    required: false
  context:
    description: 'Build context'
    required: false
    default: '.'
  dockerfile:
    description: 'Dockerfile path'
    required: false
    default: 'Dockerfile'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DOCKER_REGISTRY: ${{ inputs.registry }}
    DOCKER_USER: ${{ inputs.username }}
    DOCKER_PASS: ${{ inputs.password }}
    DOCKER_REPO: ${{ inputs.repository }}
    DOCKER_TAG: ${{ inputs.tag }}
    DOCKER_CTX: ${{ inputs.context }}
    DOCKER_FILE: ${{ inputs.dockerfile }}
