
name: 'Docker builder'
description: 'Build docker image and push to specific registry'
branding:
  icon: 'box'
  color: 'green'

inputs:
  username:
    description: 'Docker username'
    required: true
  password:
    description: 'Docker password'
    required: true
  tags:
    description: 'Image tag, including repo path'
    required: true
  registry:
    description: 'Docker registry'
    required: false
    default: 'docker.io'
  context:
    description: 'Build context'
    required: false
    default: '.'
  dockerfile:
    description: 'Dockerfile path'
    required: false
    default: 'Dockerfile'
  platforms:
    description: 'Target platforms'
    required: false
    default: 'linux/amd64,linux/arm64'

runs:
  using: 'docker'
  image: 'Dockerfile'
